dev:
  main: holleWord

#rabbit配置
spring:
  rabbitmq:
    # rabbit地址
    host: 127.0.0.1
    # rabbit端口号
    port: 5672
    # 用户账号和密码
    username: guest
    password: guest
    #rabbit项目名，每个virtualHost的队列是隔离的，相当于数据库
    virtual-host: /rabbit
    publisher-confirms: true
    listener:
      direct:
        #设置监听为手动答应模式
        acknowledge-mode: manual
