dev:
  main: holleWord

#rabbit配置
spring:
  rabbitmq:
    # rabbit地址
    host: 127.0.0.1
    # rabbit端口号
    port: 5672
    # 用户账号和密码
    username: guest
    password: guest
    #rabbit项目名，每个virtualHost的队列是隔离的，相当于数据库
    virtual-host: /rabbit
    #开启Publisher Confirms 模式，消息发送到交换器后触发回调。
    #publisher-confirms: true
    #开启PublisherReturn 模式，交换机将消息发送到对应队列失败时触发
    #publisher-returns: true
    listener:
      #设置监听容器（Listener container）类型，如不设置，将会默认为SimpleRabbitListenerContainerFactory，且下面的direct配置不生效
      type: direct
      direct:
        #设置监听为手动答应模式
        acknowledge-mode: manual