dev:
  main: holleWord

#rabbit配置
spring:
  rabbitmq:
    # rabbit地址
    host: localhost
    # rabbit端口号
    port: 15672
    # 用户账号和密码
    username: guest
    password: guest
    #rabbit项目名，每个virtualHost的队列是隔离的，相当于数据库
    virtual-host: /rabbit
